server:
  port: 8082

spring:
  application:
    name: Eureka-Server-B

eureka:
  instance:
    hostname: Eureka-Server-B
  client:
    service-url:
      defaultZone: http://127.0.0.1:8081/eureka/,http://127.0.0.1:8082/eureka/,http://127.0.0.1:8083/eureka/